### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by whiteHagrid** [hop-protocol/hop-airdrop#174]
# Related Addresses

0x0fcfebf31fa34f1d7aca854a752bfc85564e7b3f (Main wallet)

0x0eae0b9ee583524098bca227478cc43413b7f4b9

0x0d296d02f3cd8cc3051ca1b18314e9eef8e721b8

0xa4cff481cd40e733650ea76f6f8008f067bf6ef3

0x8eb60797eac90e9118ecbafb383ea6587aa9701e  

0x1dbd7505b0c5b5f47df310183422ea4f55ba4119  

0x746e031d07dc1bef47a36ad8ed7af966c759079c

0x8b5b3aeda1e7755409868dbbe4a2437b9385a643

0x4022332d5dd4a890549c1dff2a7111b052c1b733

0x1dbd7505b0c5b5f47df310183422ea4f55ba4119

0xa617acfb65dea26b8247c879db626166e7f030af

0x5ebb48aa45c98e3e24f7ef88f584908710d27380

0xbe2e95087afac9d4a3ce4f61d88d20771f88df6a

0x73b2ced43e685246ea6505b526f1441a66050259

0x09bfa6c5541c527de7c7ecaf53039ef9a902aeb6

0xd1b4612fcb4298168e33363543a56150298cf7f0

0x79c1b3515c349d484816cc5d4e387b8c46b26fc0

# Reasoning

The attacker used multiple wallets to create LPs and wanted to sybil attack hop protocol with control of massive HOP allocation. Main wallet
0x0fcfebf31fa34f1d7aca854a752bfc85564e7b3f created LP tokens and transfered funds to multiple wallets on the list above . Inside those wallets he bridged and
created LPs. On some wallets he forwared eth to the next wallet and again bridged and created LP. His whole allocation is around 400K tokens

# Methodology

Used LPs onchain analys to track down the main wallet,then followed the funds on multiple wallets and saw a patter of LP creation and same amounts of funds
transfered.

# Rewards Address

0xea740cE1E29594f83acC57B24848567ae8D75690

**Comment by shanefontaine** [comment]
@whiteHagrid 

Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

It looks like most of yours were submitted with #167 .
