### ISSUE TITLE
Sybil Attacker Report - Multi-address 1 user

### ISSUE THREAD

**Issue by r4bbit2015** [hop-protocol/hop-airdrop#185]
# Related Addresses
Please wait until all the data is processed and I will upload the file
```
```

# Reasoning
The transfer parties of these addresses also have airdrop rewards, both of them are controlled by 1 person, which is not fair for people who have only one address to say, the airdrop rewards should be given to a real user, not 2 addresses of 1 user

Guess how many addresses of this type there will be from the 30,000 addresses?
1 of their addresses should be removed from the airdrop rewards, it's good for the community!
Of course they could be more than 2 addresses, let's keep trying to find these guys

# Methodology

```

def get_all_address():
    urls = "https://raw.githubusercontent.com/hop-protocol/hop-airdrop/master/src/data/eligibleAddresses.txt?token=GHSAT0AAAAAABH3XLL7B2HXRO5VHMIYZURSYTUCDMQ"
    res = requests.get(urls)
    # print()
    address_lists = res.text.split('\n')
    # print(len(address_lists))
    #32806
    return address_lists

def is_airdrop_address(address):
    urls = f"https://airdrop-api.hop.exchange/v1/airdrop/{address}"
    res = requests.get(urls)
    data = res.json()
    # print(data['data'])
    if data['data']:
        return False
    else:
        return True


def main():
    address_lists = get_all_address()
    ok_address_lists = []
    count = 1
    for address in address_lists:
        all_ts = get_eth_history(address)
        first_from = all_ts['result'][0]['from']
        if is_airdrop_address(first_from):
            ok_address_lists.append(address)
            with open("double_address", 'a') as f:
                f.writelines(address + "\n")


        count = count + 1
    for add in ok_address_lists:
        print(add)


```
# Rewards Address
0xDCF76dEFb31E6C2493e5bf70106Af9ecD0067634
-->

**Comment by dextereth** [comment]
the criteria should be 20+ address correlation

**Comment by r4bbit2015** [comment]
> 

No, this is a different type of potential air-drop attack

**Comment by r4bbit2015** [comment]
> the criteria should be 20+ address correlation

Looking forward to the final results? See how many separate real users there are in the 30,000 addresses, LOL

**Comment by SanchoPanza1337** [comment]
You should read the team then, because your criteria is flawed when you say "The transfer parties of these addresses also have airdrop rewards, both of them are controlled by 1 person, which is not fair for people who have only one address to say, the airdrop rewards should be given to a real user, not 2 addresses of 1 user" But the team said several times that people can have multiple wallets on LP and its ok, since the rewards will be the same. And then Chris also said "The threshold for our own review was 8 or more addresses. They only got eliminated if they all did the exact same thing for farming purposes. If you legitimately used 8 or more addresses for different things, all will receive tokens."
If your criteria goes ahead you might end with 1k or 2k real wallets with no connections, and you will cut 10k+ users out, then the token will be super concentrated and its worse than cutting those with 2 or 3 wallets connected. There is a reason why they didn't do that (ofc they know there are people with 2 or 3 or 4 wallets, you are not making them find something new)

**Comment by r4bbit2015** [comment]
> 那你应该看一下团队​​，因为你的标准是有缺陷的，当你说“这些地址的转账方也有空投奖励，他们都被1人控制，这对于只有一个地址的人来说是不公平的，空投奖励应该给一个真实的用户，而不是一个用户的两个地址”但是团队多次表示，人们可以在 LP 上拥有多个钱包，没关系，因为奖励是一样的。然后 Chris 还说：“我们自己审查的门槛是 8 个或更多地址。只有当他们出于农业目的都做了完全相同的事情时，他们才会被淘汰。如果你合法地将 8 个或更多地址用于不同的事情，所有人都会收到代币。” 如果您的标准继续执行，您可能会以 1k 或 2k 个没有连接的真实钱包结束，并且您将削减 10k+ 用户，那么令牌将超级集中，并且比削减 2 或 3 个连接的钱包更糟糕。他们不这样做是有原因的（他们知道有些人有 2 个或 3 个或 4 个钱包，你不会让他们找到新的东西）

OK.
