### ISSUE TITLE
Sybil Attacker Report-"Report" abusers

### ISSUE THREAD

**Issue by han78923** [hop-protocol/hop-airdrop#237]
I'm sorry to report it this way.I didn't find another effective way...

 I will report "reported" abusers;

At present, he has submitted a total of 28 questions, of which 11 have been proved to be framed. I think he has hurt too many real users. He has not paid any price, but increased the labor cost to the operators and hurt the real users;
This person's behavior is equivalent to "airdrop Hunter". We encourage everyone to report the air drop hunter, but we do not encourage the abuse of the reporting function. I suggest canceling all his reporting rewards;

His url  https://github.com/GreyPK

![unknown](https://user-images.githubusercontent.com/90543468/167389105-af3b2f94-f052-48a3-87ab-4fbab33eb787.png)

If there are potential rewards.....
# Rewards Address

0x1F3863672D3725aC40dAC452eE5454Cf3D118B4A

**Comment by han78923** [comment]
https://github.com/antoncoding?tab=overview&from=2022-04-01&to=2022-04-30

and this one

At present, he has submitted a total of 16 questions, of which 10 have been proved to be closed,most of the reason is that the address he found is not in the list;

His technical strength is very strong, but I think his report is not rigorous,

At the same time, his behavior is more like reporting for "reward", which is immoral and will bring harm to more users;

![image](https://user-images.githubusercontent.com/90543468/167390214-f0600b8e-940b-40a7-92ef-f7096817f9d4.png)

**Comment by GreyPK** [comment]
Hi, han78923. I closed my 12 entries myself. That was 3 days ago, the same day I discovered inaccuracies in the algorithm for determining sybil and closed 12 of my 15 posted entries.

It is unlikely that contributors are accepting entries into processing immediately after publication because of the large number of entries. Judging by the comments of the contributors, probably 10th-20th entries are now under review.
The number of my first entry that I closed was 77th. I doubt that the contributors have considered them. In the future, I will check the data more carefully before publishing.

What possible harm could there be to actual users? If the user is not an infringer - the contributors will never add them to the infringer list.

**Comment by Firsttimer001** [comment]
> Hi, han78923. I closed my 12 entries myself. That was 3 days ago, the same day I discovered inaccuracies in the algorithm for determining sybil and closed 12 of my 15 posted entries.
> 
> It is unlikely that contributors are accepting entries into processing immediately after publication because of the large number of entries. Judging by the comments of the contributors, probably 10th-20th entries are now under review. The number of my first entry that I closed was 77th. I doubt that the contributors have considered them. In the future, I will check the data more carefully before publishing.
> 
> What possible harm could there be to actual users? If the user is not an infringer - the contributors will never add them to the infringer list.

You falsely accuse real users of being airdrop farmers, many persons like you compiled dozens of addresses where many were't eligible to begin with, and some only LP's which the report says swap and send.

**Comment by GreyPK** [comment]
Firsttimer001, If I have somewhere indicated the wrong wallet - please write in the appropriate entries. And If there was an error I will remove it.

**Comment by SanchoPanza1337** [comment]
No one takes 1 minute to read what the team said, you have reports with less than 10 wallets (its not the criteria for reporting), you have reports with multiple LP airdrop (its not the criteria for reporting), you have reports that seem copy paste from other users, etc.... And then they dont take the enough time (when there are two-three weeks) to do their proper job, seeing the guy closing 12 of his 15 reports its a joke.
Doing reports its free and at this point you can open a report and say the 30000 airdrop wallets are flagged, some of them interacted to others, pls ser Hop send rewards to 0x0000000000000000000
People can do this because its free and they have NOTHING to lose, they should allow people with airdrop to report others, and if they do a bad job reporting others they lose 25% or something.

**Comment by han78923** [comment]
Before you shut down, you thought they were witches,

So how do you prove that the algorithm is not illogical?

You yourself have closed a part in other people's questions.

Hey, man, don't deny that you have wrongly reported many real users in order to get airdrop,

Although you shut down later, who can guarantee that what you report now is not a real user?

**Comment by GreyPK** [comment]
han78923, my algorithm in the 12 closed entries was as follows: I was looking for a polygon's transaction that used Disprerse.app, in which 20+ recipients are members of the airdrop.
I assumed that if one address sends funds to 20+ airdrop addresses, then that confirms their connection. 

Then user rotate-eth, pointed out that in such transaction for example there can be 830 transfers, and of them only 22 recipients of airdrop. I realized that it is special addresses send coins to very wide range of wallets, and I need to clarify algorithm: not-airdroped recipients must be minimum in DIsperse's transaction and they must use HOP in similar way. Then I closed these entries.

I'm not a robot, I can make mistakes. Even in 3rd entry, not all 516 addresses were called, only 471. So what?
Where human works, there can be no guarantee that everything is 100% correct. That's why contributors check entries.

**Comment by han78923** [comment]
As I said, you are another kind of "air drop Hunter", you don't understand;
From the real world to the encrypted world, you need a "guide". Do you know where the first gas fee comes from after new players enter the encrypted world? In many cases, it is given by the "guide"; Because exchanges are easily deceived and illegal in some countries
t is precisely because of these "guides" that more and more players will play in the encrypted world; It is undeniable that there are many "hunters" in the encrypted world, but we also need to pay attention to the relationship between "teachers and students" in this world; Without a "guide", many players don't know what is "hop" or even what is "bridge";🤣
ou are just a person who wants to use a lot of reports to get airdrops; What you think is noble is just a kind of hypocrisy;
I will continue to browse these report posts and find "air drop hunters" like you🤣

**Comment by Bobb2906** [comment]
han78923 you need to learn how to snitch🤣

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.

It looks like both @GreyPK and @antoncoding have completely valid reports in this repository.
