### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by pileofscraps** [hop-protocol/hop-airdrop#377]
# Related Addresses

```
0xd942010f8808996a682502df5d5b2af7fcbc7318
0xf201b83ab58b2e72cdcf8ffffd05fdc43032abee
0x8c2e843664be468522769b0d1b3b604a17962249
0xcbcc36af59675e7b291dcbcf7c5adc7b9894969d
0x75c1e14cd2d114686bd5b765fcfe376176e41f1f
0x90b0dec1f1bba847015904c115b8a99bf22925c5
0xb7919ad276b1e77e29b8ae75837517a1522f8d0a
0xaf43d3c6a1362ca33fbba27d16959deb454f72ae
0x52c881b5c39ecb74e1f17c6ac13868845cbc3955
0xafd0ceb854f1de3425e5addadad5fea81abb471a
0xa2dacd1fafc4168511e9d9086405a780874f6384
0xb17a1def6a0d6f1e18c32e844aff98080477cd98
0x4bc25a712b87c1e4a42df9ffac3662fe467b7e9a
0x5e82ac3fe0632fd7818fa280bd4ac687ab6c8c89
0x294c5d65620ed122e8e84d2241db5c67feb67907
0x8c2e843664be468522769b0d1b3b604a17962249
0x6a16683bb8654433d67f6a9e0dc9eb563456823e
0x8ebc08c08b79c7ee7de645fde878d0dbcdbf93ae
0x501783e585936116220b5028c4c22dc9fdb991bc
0x285ab8b73531a59bcb01b7f2028a66aa377e697b
0xd2208b5c2091d8c847d246509ed306bd6be9d200
0x1ba1ff69f03d38af7ef40e3afdc53ad073eb4642
0xdb57f1613ef9d26af65bcc5dd197a9f31a5aa091
0x50c2b9c3acda872dd71d88aa2c198aed0b788e5b
0x4d246e41d7131ff60cd533c13bd2aafce7ab1265
0x40cf224a5e91949bd2ba4276d046c4680c8d646c
0x4dc23e91fcd7693551f99642bc1e0ed4664fbddd
0xec4a6612e32230bf2771d2a371a7b062aea1e420
0x68c41a057e660bc9dfbbaf83835efb65c4f379cc
0x2de5ce502ec02a365700a0b9251fdd424aefb2d9
0xcef9f507f4fb76d8f4997a52b64b59be059c4945
0x720fcb0a03397b34414c162dd794e6661c04c719
0x0bb957cdca465166f427873c5046d46b7a1f33ec
0x387b818c4f51d1e78d4e1535bc4b654a2a83d6af
<----------------->
0xb23691043293de4deeae3b565bd33bc059f264eb
0x1cccff3de9b0a7c466acb31f33910691f1cb6e14
0x80d19ec3a87f45e83c33547d8fb56f51266419b9
0x4f647966968b1f417f2181327d333575ad0b46d3
0x8aa3e3da214d410440ec56814b5999b4f1d15c82
0x80d19ec3a87f45e83c33547d8fb56f51266419b9
0x5691df0ddc35ce430856a333566e2b19b7c9abcc
0x8752c42677daa72fd1c54f8bb480f5cf0b8bfda3
0x16326d7b00cb6175fe97631ac6e957ce346d1643
0xa32a1f1c227b7b5d8251465f9398ac70675af6d8
0xaea79e61d658690b2cc0c4078d37ab18cfd2afaf
0xb361e41e92870c8a05587665c73aa7b8c5f5f609
0xb713df754bbf37db676e2b49d62d5f9532b56746
0xcb78dac9a2c43c62e454d62184f72373917e3ae7
0xc83a13319561e3c080c9b8ef31b8ecf6c1e63c68
0xcc06ac76b8e778d75af1cecc57561c0197160f68
0xbd985b4632a3ad19ad54cb75db7c3fb53a490fb8

```

# Reasoning
![hop-sybil-hunting](https://user-images.githubusercontent.com/42047110/168989635-8b35ddc0-ad12-4847-b7d5-d56575541d63.png)

All addresses are connected by on-chain transfers between each other. The sybil attacker exhibits two distinct patterns with the blue-colored edges denoting the first and the green-colored edges denoting the second.  

NOTE: Orange-colored nodes in the graph denote addresses that serve as on-chain connections between all sybil accounts where transfers occurred/were funneled through but were not included in the submission set due to slight deviations from the 2 patterns outlined in this report.

## Pattern 1:
For nodes connected by blue edges, the attacking address used Hop to ping pong back and forth between Gnosis and Polygon, transferring the same value net fees from one chain to another and back sequentially. All transactions utilize USDC (1 tx in USDT) approximately 1000 ± 250 dollars in value. Additionally, each batch of transactions within each address were made within a very small timespan (on the order 1-3 hrs)

An example of this is: 
https://explorer.hop.exchange/?account=0x4bc25a712b87c1e4a42df9ffac3662fe467b7e9a

NOTE: Pattern 1 was found by observing on-chain transfers traced on Ethereum mainnet. Upon further investigation, it was apparent that a connected set of addresses, namely Pattern 2, was connected to the first pattern by tracing transfers between the hub address (0xb23691043293de4deeae3b565bd33bc059f264eb) and its associated spokes on Avalanche. We were able to make this connection across chains due to the fact that the sybil attacker overlapped a few transactions both on Ethereum mainnet and Avalanche. Specifically transfers between 0x1100cc5c25befe926d03d3375d3e813d34e76a8e <->  0xb23691043293de4deeae3b565bd33bc059f264eb and 0xb23691043293de4deeae3b565bd33bc059f264eb <-> 0x80d19ec3a87f45e83c33547d8fb56f51266419b9 occurred on both networks denoting the connection in the 2 patterns.

0xb23691043293de4deeae3b565bd33bc059f264eb Hub Graphic:
<img width="1065" alt="Screen Shot 2022-05-18 at 12 25 40 AM" src="https://user-images.githubusercontent.com/42047110/168990054-673de61a-d6d4-478d-a4eb-bae76074f96a.png">

https://snowtrace.io/txs?a=0xb23691043293de4deeae3b565bd33bc059f264eb&p=1

## Pattern 2:
For nodes connected by green edges, the attacking address would use Hop multiple times over a period of several hours, conducting repeated exchanges primarily from Gnosis to Polygon. All transactions typically utilize 200-300 dollars in DIA, USDC, or USDT and happen within hours of each other within each account. In aggregate, this pattern occurred over the span of about a week from Jan 15, 2022 - Jan, 24 2022. 

An example of this is: https://explorer.hop.exchange/?account=0x1cccff3de9b0a7c466acb31f33910691f1cb6e14

# Methodology

The reported addresses were discovered primarily using scripts that scraped Ethereum and Avalanche mainnet across all eligible addresses. In particular, the scripts searched for multiple eligible addresses clustered around each other by tracing shared on-chain transfer history for connected addresses. The base of the script revolved around previously submitted code by other sybil hunters which they had originally used for verification. In this case, the code was expanded to brute-force search the entire list of eligible addresses. Once a cluster was found, a combination of manual tracing / programmatic tracing of transfers and cross-referencing associated addresses with the eligible address list led to the discovery of the patterns outlined in this report.
 
# Rewards Address

```
pileofscraps.eth
```

**Comment by shanefontaine** [comment]
Thank you for your report @pileofscraps. We have verified that the addresses in this report are Sybil attackers.

The report included 45 eligible addresses as Sybil attackers which means you are eligible for 13983.159831042749846212 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).

Please note that some addresses were considered invalid due to the fact that they did not exactly follow some of the patterns of the other addresses and there was a non-negligible probability of eliminating legitimate users. These addresses that were not considered are:

```
0x4d246e41d7131ff60cd533c13bd2aafce7ab1265
0x285ab8b73531a59bcb01b7f2028a66aa377e697b
0x80d19ec3a87f45e83c33547d8fb56f51266419b9
0x5691df0ddc35ce430856a333566e2b19b7c9abcc
```

The qualified addresses are as follows:

```
0x4dc23e91fcd7693551f99642bc1e0ed4664fbddd
0x1ba1ff69f03d38af7ef40e3afdc53ad073eb4642
0x40cf224a5e91949bd2ba4276d046c4680c8d646c
0xd2208b5c2091d8c847d246509ed306bd6be9d200
0xdb57f1613ef9d26af65bcc5dd197a9f31a5aa091
0xec4a6612e32230bf2771d2a371a7b062aea1e420
0x8c2e843664be468522769b0d1b3b604a17962249
0x501783e585936116220b5028c4c22dc9fdb991bc
0x52c881b5c39ecb74e1f17c6ac13868845cbc3955
0x90b0dec1f1bba847015904c115b8a99bf22925c5
0xb7919ad276b1e77e29b8ae75837517a1522f8d0a
0xf201b83ab58b2e72cdcf8ffffd05fdc43032abee
0x50c2b9c3acda872dd71d88aa2c198aed0b788e5b
0x75c1e14cd2d114686bd5b765fcfe376176e41f1f
0xcbcc36af59675e7b291dcbcf7c5adc7b9894969d
0xaf43d3c6a1362ca33fbba27d16959deb454f72ae
0x6a16683bb8654433d67f6a9e0dc9eb563456823e
0x294c5d65620ed122e8e84d2241db5c67feb67907
0xafd0ceb854f1de3425e5addadad5fea81abb471a
0xd942010f8808996a682502df5d5b2af7fcbc7318
0xb17a1def6a0d6f1e18c32e844aff98080477cd98
0x5e82ac3fe0632fd7818fa280bd4ac687ab6c8c89
0xa2dacd1fafc4168511e9d9086405a780874f6384
0x4bc25a712b87c1e4a42df9ffac3662fe467b7e9a
0x8ebc08c08b79c7ee7de645fde878d0dbcdbf93ae
0xbd985b4632a3ad19ad54cb75db7c3fb53a490fb8
0x8752c42677daa72fd1c54f8bb480f5cf0b8bfda3
0xc83a13319561e3c080c9b8ef31b8ecf6c1e63c68
0xcb78dac9a2c43c62e454d62184f72373917e3ae7
0x1cccff3de9b0a7c466acb31f33910691f1cb6e14
0xcc06ac76b8e778d75af1cecc57561c0197160f68
0x68c41a057e660bc9dfbbaf83835efb65c4f379cc
0x387b818c4f51d1e78d4e1535bc4b654a2a83d6af
0xcef9f507f4fb76d8f4997a52b64b59be059c4945
0x720fcb0a03397b34414c162dd794e6661c04c719
0x0bb957cdca465166f427873c5046d46b7a1f33ec
0x2de5ce502ec02a365700a0b9251fdd424aefb2d9
0xb23691043293de4deeae3b565bd33bc059f264eb
0xa32a1f1c227b7b5d8251465f9398ac70675af6d8
0xaea79e61d658690b2cc0c4078d37ab18cfd2afaf
0x4f647966968b1f417f2181327d333575ad0b46d3
0xb713df754bbf37db676e2b49d62d5f9532b56746
0xb361e41e92870c8a05587665c73aa7b8c5f5f609
0x16326d7b00cb6175fe97631ac6e957ce346d1643
0x8aa3e3da214d410440ec56814b5999b4f1d15c82
```

**Comment by shanefontaine** [comment]
@GreyPK Those addresses do not follow the "ping-pong" pattern as described by @pileofscraps . Because of this, it is difficult to consider them related in the same group. The transactions to/from each other are not enough proof alone.

https://explorer.hop.exchange/?account=0x5691df0ddc35ce430856a333566e2b19b7c9abcc

**Comment by dai114** [comment]
I borrowed AAVE from my friend (my friend is also exposed to the crypto world under my leadership, and his community members have 53 members, which is a good result)

Aave was borrowed to allow me and my crew to do a learning platform task (time and quota limited), so you need to complete it in a short time, otherwise you won't get a reward, that's why trading on Snowtrace;

The "teacher-student" relationship is very common for beginners, and MY approach to blockchain is also led by my teacher.  If some people force a transaction to establish a connection, this is not acceptable to me. Due to the public nature of blockchain, this means that the whole crypto world will be full of witches (every address will have a large number of address associations).

I emphasize again and again that we are a small community, mostly of beginners who don't even know how to use mnemonics at first;
I need to provide them with tutorials, gas fees, and even the cost of playing dApp; Of course I'll charge my tuition in other currencies;
What exactly is Sybil? Does the development team have their own definition?Only 10-20 address？Is this definition insulting "Sybil"? Even a "DDOS" attack needs to reach a certain scale to be called this name; if you regret issuing airdrop rewards, please change the previous condition of "20 addresses" to review "1 address"；
I teach them step by step, I teach them how to operate, there are similarities in behavior, but they are fundamentally different from Sybil; I want my members to learn in the crypto world, and if there is some benefit to it, it will definitely motivate them;
Shouldn't this model also be allowed? If the "community" mode is not allowed, please send a notice.

**Comment by dai114** [comment]
We are not "Sybil" why self-report？What information do I need to provide to prove that these addresses belong to different people?

**Comment by dai114** [comment]
this is my member's address
0xb23691043293de4deeae3b565bd33bc059f264eb
0xa32a1f1c227b7b5d8251465f9398ac70675af6d8
0xaea79e61d658690b2cc0c4078d37ab18cfd2afaf
0x4f647966968b1f417f2181327d333575ad0b46d3
0xb361e41e92870c8a05587665c73aa7b8c5f5f609 
0x16326d7b00cb6175fe97631ac6e957ce346d1643
0x8aa3e3da214d410440ec56814b5999b4f1d15c82
Other addresses have nothing to do with me, and it can be seen from the behavior that I basically interact with my member addresses 10 times (because they all follow the same tutorial)

**Comment by dai114** [comment]
What I'm trying to say is that if my and my members' actions trigger certain conditions that lead to being identified as "Sybil" by the team; I accept the results with reservations,
But if someone deliberately and indiscriminately associates addresses; I don't accept this result; the cost of making rumors is too low, they just need to copy the previous proposal and add a few addresses to make rumors, costing the team and the reported person a lot of money Energy and time to review, this is problematic.[shanefontaine](https://github.com/shanefontaine)

**Comment by shanefontaine** [comment]
> What I'm trying to say is that if my and my members' actions trigger certain conditions that lead to being identified as "Sybil" by the team; I accept the results with reservations

I now understand. This is correct. Your members' addresses triggered the conditions that classify a group as Sybil attacekers.

**Comment by dai114** [comment]
OK, glad I made this clear;
Two questions now (no instant messenger, that's all, sorry)
First: #377 has already reported these addresses, so the report in #379 should not stand! (The first is that the two are repeated, and at the same time in #379, there is a malicious association, and none of our members' addresses are related to 0x4Fa267b2ae26416872Cea64E5F275D93079927a0
; 0x6eBA5B898e9E24C1Fd0062025eD96fA751170eC4 with any interactive behavior)
Second: I have a lot of members, they have 1-5 addresses respectively, I can provide their respective signatures and our previous transaction records (realistic); should the "behavioral group" formed by these people be identified For "Sybil"?

**Comment by shanefontaine** [comment]
1. Report #379 has been updated and does not include any eligible addresses listed here. [Here](https://github.com/hop-protocol/hop-airdrop/issues/379#issuecomment-1130579190) is the comment that states this.
2. We are only considering groups of 10+. If there are 10+ addresses in your groups that meet the definition of Sybil, please self-report before someone else does.

Thank you for the questions.

**Comment by dai114** [comment]
0x4Fa267b2ae26416872Cea64E5F275D93079927a0
0x6eBA5B898e9E24C1Fd0062025eD96fA751170eC4
0x1100cc5c25befe926d03d3375d3e813d34e76a8e
0x6C13FC8EF50144A21702415d57ece0A09879fCFb
According to your previous description, these four addresses cannot be counted as Sybil

**Comment by dai114** [comment]
https://github.com/hop-protocol/hop-airdrop/issues/377#issuecomment-1130877642
As described in your own rules; these 4 addresses, with no interaction or apparent behavior, why should they be banned? It's not "Sybil" just because someone put them together on purpose

**Comment by shanefontaine** [comment]
@dai114 Those four addresses were submitted in a group of 20 that was reviewed and deemed a valid Sybil attacker group. Because they fit the definition of a Sybil attacker in #379 and were approved, they are labeled as Sybil attackers.

**Comment by dai114** [comment]
The first two addresses and other addresses do not have any transactions, why are they confirmed? And the last two addresses, with a lot of hop and other transactions, they don't fit the way you mentioned in 377

**Comment by dai114** [comment]
https://github.com/hop-protocol/hop-airdrop/issues/377#issuecomment-1131011368
At the same time, the records here can only prove the relationship between the two address groups in the lower right corner. This is just like our previous communication. The behavior of our members is expected, and I accept this result;
But the addresses marked in yellow, and the lower-left, upper-left, and upper-right groups, are irrelevant to me;

**Comment by shanefontaine** [comment]
> At the same time, 0x6C has nothing to do with 0x68

`0x68c41a057e660bc9dfbbaf83835efb65c4f379cc` and `0x6c13fc8ef50144a21702415d57ece0a09879fcfb` have similar behaviors on Hop protocol, they have similar behaviors on Avalanche, they send each other funds on Avalanche ([1](https://snowtrace.io/tx/0x9f845123d3f85dfaaf0d0e12cdff647e88e2d24ed7d67222871c2c2a2f71f0a2), [2](https://snowtrace.io/tx/0xa2eed545e2434f3674346381a036be1695e3d3d2b1c2894a186a47a863274761)), `0x6c13fc8ef50144a21702415d57ece0a09879fcfb` sends `0x68c41a057e660bc9dfbbaf83835efb65c4f379cc` funds on [Heco](https://hecoinfo.com/tx/0xea2bff5e31ec8b9acb38f4f828e8fad3506e58b5c57cfee4def4618d2676f921).

These addresses exhibit Sybil behavior, were reviewed thoroughly, and were marked as attackers with the same conditions that all other addresses were.

**Comment by dai114** [comment]
0x68c41a057e660bc9dfbbaf83835efb65c4f379cc
0x6c13fc8ef50144a21702415d57ece0a09879fcfb
I can like to provide you with the chat records at that time (I don't know how to upload pictures on git, can I pass my dis friends). . . Because the avax of 0x6c is not enough, I borrowed it from him, and the next day, I returned it to him; because the task of using avax is limited to 2000 places, it needs to be completed within 1 day, otherwise it will expire;
As for the lower left and lower right corners of 377, there are two separate groups;
