### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by jumaq** [hop-protocol/hop-airdrop#95]
# Related Addresses

0xbB777059731726fb990faC2687Fa6C1F2924D4Cd
0xC65cA30522873e9ddcA4158F79Dc9ECD1b823932
0xda8639ebaDE510607414fE396E98171280EE86f1
0x71Fb48f6d9b023B095Efb392a1Da359c873A0d46
0x351b2f26F5b7B04F8f1CC42bfdd180c5B9A90303
0xbb3652E7A004f15847e85a3c5C87904926138fB8
0xf8C246C1B26535aa3771211f6eCc71617A46b4c1
0xF0BB0C9F8234f7E2eD95f4d245FC3c17a993FE2b
0x55B38ED25ea7961F44722419B05e324d7d3aA321
0x644814f9Ea24110BC17e01b1127308972360d80E
0xfE6F9DE6Cae3dFacBA51fA88067477D65a02f777
0x4C07D2c59690163c0212a4eBC7182821B3b4bCc5
0x22675E69C276cf2D58934123B652FC420110ff02
0x18005F41c9881F7C1d21e81b1C610381921e5b07
0x76E194f8361E7eadf6565C24967312B1e3277661
0x9f479Ae664F0BEdA22c64E5F48a150A6f85ACb77
0xDa3605D79BC9e6dDef9bC8166C922cf7fd7C01a0
0xcF683F870f0E5E1127E87903F4d41efD4438d274
0xA3364075CB95d731d605363a66ae8d6D1aDA2D7f
0x1C0c89581928af321Df09769fc77eC50175E8e9e
0xCEed5de12428369816Cd22d1bA71463FC4C4C73E
0x124Ee858516114b5BC10e15A7dA832Fb87287Af3
0xE3B8681778882bdd121b51eADA0De2B9088398Df

# Reasoning

The address listed may not be complete. It may only be part of many associated addresses.

These addresses have very similar ens names, and there is an obvious transfer association between them. All address associations can be found on etherscan. This is only the transaction record of layer1, and there may be more key addresses on other chains.

Such as
wwwicp.eth
gearbaby.eth
zkslink.eth
wwwuni.eth
nbanft.eth
wwwmeta.eth
gearbtc.eth
lixinya.eth
moreairdrop.eth

-->

# Methodology
Check by hand on etherscan.io

# Rewards Address

**Comment by jumaq** [comment]
Rewards Address:
0xe7b0155887f55A0DC43d1eDc9D74694b489411b7

**Comment by jumaq** [comment]
These two addresses are also related to the address I reported.

0x1f69Ee6C9dB214362368608CD7D886Cc64142270
0x1f8A7898d5237fF11Ea52D85Cc3b633E6Be9A939

https://etherscan.io/tx/0x4ae4af981725f788a3a8d765202fd7d4c9250220785a5b13570cf9ecc1e38ae9

**Comment by shanefontaine** [comment]
@jumaq

Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

Please note that addresses may be connected by sending funds to their friends, OTC deals, direct NFT trades, etc.
